runtests.py: fix exception in scantests()
When run with the "-l modules" or "-l classes" options runtests.py
was failing with exception:
  ValueError: too many values to unpack (expected 3)
Problem was too many dots in test names due to them being moved
into a subdirectory some time ago.