cgi: make edconf, edform cgi templates usable by jmapp
Applied a more general method to make cgi templates compatible
with jmapp.  Specifically, set variables that cgi normally supplies
but jmapp doesn't.  Set 'session' variable from 'user' when calling
from jmapp.  In jmapp.py, pass form values to view using Rq.values
rather than Rq.form (the former contains both GET and POST values,
the latter only GET), and allow POST where the cgi templates want
to use it.  (In some cases POST is used by the cgi forms only to
hide the sid values, something not needed by jmapp which consequently
changed the method in those cases to GET; they can be changed back
to GET only after cgi is fully dropped.)

The above changes also fix error in edform.jinja under CGI.  The
previously present line:
  {% set dbg=none if dbg is not defined %}
caused an exception when template was used under CGI:
  jinja2.exceptions.UndefinedError: the inline if-expression on line 28 \
  in 'user.jinja' evaluated to false and no else section was defined.

With the above changes applied, the edform.jinja and edconf.jinja
templates are usable by both the cgi and jmapp implementations.